FROM ubuntu:20.04

LABEL description = "Imagen para desarrollar con php"
LABEL mainteiner = "Diana Meneses"
LABEL version = "0.1"

RUN apt update 
RUN apt install -y php
RUN apt install -y mcr.microsoft.com/azureiotedge/sqlite
RUN apt install -y php-pip
RUN apt install -y mcr.microsoft.com/azureiotedge/sqlite-pip